### ISSUE TITLE
Error: not found

### ISSUE THREAD

**Issue by egll-tech** [ghooks-org/ghooks#281]
For some unknown reason, it throws me this error every time I run any git command. I'm using git modules for this project.

```
/home/eagle/Projects/repository/node_modules/findup/index.js:94
  throw new Error('not found');
  ^

Error: not found
    at Function.module.exports.sync (/home/eagle/Projects/repository/node_modules/findup/index.js:94:9)
    at commandFor (/home/eagle/Projects/repository/node_modules/ghooks/lib/runner.js:37:26)
    at run (/home/eagle/Projects/repository/node_modules/ghooks/lib/runner.js:10:19)
    at Object.<anonymous> (/home/eagle/repository/.git/hooks/post-merge:11:18)
    at Module._compile (internal/modules/cjs/loader.js:945:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:962:10)
    at Module.load (internal/modules/cjs/loader.js:798:32)
    at Function.Module._load (internal/modules/cjs/loader.js:711:12)
    at Function.Module.runMain (internal/modules/cjs/loader.js:1014:10)
```

It's trying to find the package.json, but it's skipping it, even when it's in the root folder.

```
OS: Manjaro x64 18.1.1
Git: 2.23.0
Node: 12.11.1
```

**Comment by gkarapeev** [comment]
Any insights on this one?
